---
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Statistical Learning, Machine Learning & Artificial Intelligence

*Overview*

The course introduces the most important algorithmic and statistic machine 
learning tools. The first part of the course focuses on the statistical 
foundations and on the methodological aspects. The second part is more 
hands-on, with practical applications to help develop the necessary software 
skills.   

The course aims at teaching a methodological and practical overview to 
statistical learning methods. The emphasis is on the applications and 
state-of-the-art techniques are presented through hands-on tutorial 
with **R**. The focus will be on business-oriented libraries allowing to 
integrate statistical models into production-ready tools.  


## General Information

- [Course Descriprion (for Students)](https://marcozanotti.github.io/statlearning-course/general-infos/statlearn_description.html)
- [Course Descriprion (for Business Experts)](https://marcozanotti.github.io/statlearning-course/general-infos/statlearn_description_business.html)  
- [Syllabus](https://marcozanotti.github.io/statlearning-course/general-infos/statlearn_syllabus.html)  


## Materials

- [Lectures](https://github.com/marcozanotti/statlearning-course/tree/master/R)  
- [Lecture 0 - Tidyverse](https://marcozanotti.github.io/statlearning-course/R/statlearn_lecture0_tidyverse.html)


## Suggested References

R Programming:

- [R for Data Science](https://r4ds.had.co.nz/)  
- [Efficient R Programming](https://csgillespie.github.io/efficientR/index.html)  
- [R Packages](https://r-pkgs.org/index.html)  
- [Advanced R](https://adv-r.hadley.nz/)

Statistics & ML:  

- [Feature Engineering and Selection](https://www.tidymodels.org/books/fes/)  
- [Tidy Modelling with R](https://www.tmwr.org/)   
- [Stacking with R](https://stacks.tidymodels.org/index.html)  
- [AutoML with H2O](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/index.html)  
- [Deep Learning with Keras](https://keras.rstudio.com/)  

Everything with R:

-   [Big Book of R](https://www.bigbookofr.com/)
