---
title: "Statistical Learning, Machine Learning & Artificial Intelligence"
author: "Marco Zanotti"
date: ""
output:
  pdf_document: default
  rmdformats::downcute:
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

&nbsp;  

The course introduces the most important algorithmic and statistic machine 
learning tools. The first part of the course focuses on the statistical 
foundations and on the methodological aspects. The second part is more 
hands-on, with practical applications to help develop the necessary software 
skills.  


## Course Structure

The course aims at teaching a methodological and practical overview to 
statistical learning methods. The emphasis is on the applications and 
state-of-the-art techniques are presented through hands-on tutorial 
with **R**. The focus will be on business-oriented libraries allowing to 
integrate statistical models into production-ready tools.     

Specific business needs may be discussed during the lectures.


## Contents

* Tidymodels Basics  
* Tidymodels Features Engineering (Recipes)  
* Tidymodels Modelling (Engines & Workflows)  
* Tidymodels Hyperparameter Tuning (Tune)  
* Ensemble Learning (Stacks)  
* Automatic Machine Learning (H2O)  
* Deep Neural Networks (Keras)  
* Explainable AI (DALEX & LIME)  

Methods:  
- Linear Regression, Logistic Regression, Ridge, LASSO, Elastic Net, MARS  
- CART, Bagging, Random Forest, XGBoost, Cubist  
- SVM, KNN, Naive Bayes    
- Multi Layer Perceptron, Deep Neural Networks  
- AutoML  


\pagebreak


## Duration & Calendar

The course has a duration of 20 hours.


## Beneficiaries

This course is intended for data scientist, data analyst, statisticians, 
IT specialists, developers, project managers and business leaders who want 
to develop the most in-demand skills to solve machine learning problems.


## Requirements

- Basic statistic and programming knowledge.
- Lecture 0 of [R Coding](https://marcozanotti.github.io/rcoding-course/)

